// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jinsmzqlnzczsgwcnqsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppbnNtenFsbnpjenNnd2NucXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NjgxNDEsImV4cCI6MjA4NTM0NDE0MX0.-VaK6Q-oPm-cxJA4xgvv3a7TfTXIecB-SJ4pwKO66Nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});